### ISSUE TITLE
tiup拓扑配置例子中tikv_servers中一个节点上配置双实例有误

### ISSUE THREAD

**Issue by liuyongnj** [pingcap/docs-cn#14795]
File: [/release-6.5/schedule-replicas-by-topology-labels.md](https://docs.pingcap.com/zh/tidb/v6.5/schedule-replicas-by-topology-labels)
配置需求：每个 zone 内有四台主机，z1 两台主机分别部署两个 TiKV 实例
有误的原文配置如下：
```
tikv_servers:
# z1
  - host: tikv-1
    config:
      server.labels:
        zone: z1
        host: h1
   - host: tikv-2
    config:
      server.labels:
        zone: z1
        host: h1
  - host: tikv-3
    config:
      server.labels:
        zone: z1
        host: h2
  - host: tikv-4
    config:
      server.labels:
        zone: z1
        host: h2
```
建议修改的配置如下（增加port配置项，用于区分同一个节点上不同实例）：
```
tikv_servers:
# z1
  - host: tikv-1
     port：20160
    config:
      server.labels:
        zone: z1
        host: h1
   - host: tikv-1
      port：20161
    config:
      server.labels:
        zone: z1
        host: h1
  - host: tikv-2
     port：20160
    config:
      server.labels:
        zone: z1
        host: h2
  - host: tikv-2
     port：20161
    config:
      server.labels:
        zone: z1
        host: h2
```
