### ISSUE TITLE
[Feature Request] - Support System Env Variables On Syncer Config file

### ISSUE THREAD

**Issue by imiskolee** [pingcap/docs-cn#914]
Hi, Team:

In this world, most projects have two environments, test and production.

We use `git` to manage changes to configuration files. It's mean we just have a single config file for test and production.  

I want to use env variables for each project environments. Its will looks like:

```toml
[from]
host = "$TIDB_HOST"
user = "$TIDB_USER"
password = "$TIDB_PASS"
port =$TIDB_PASS
```
